application: gaeimagestore
version: 1
runtime: go
api_version: go1

handlers:
# Misc. files
- url: /([^\.]+.txt)
  upload: static/([^\.]+.txt)
  static_files: static/\1.txt
- url: /.*
  script: _go_app

skip_files:
# Hidden files:
- ^(.*/)?\..*$
# YAML, Python, CoffeeScript, markdown, shell:
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*\.ya?ml$
- ^(.*/)?.*\.coffee$
- ^(.*/)?.*\.markdown$
- ^(.*/)?.*\.sh$
# Misc.
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*/RCS/.*$
